config/routes.rb
Rails.application.routes.draw do
  resources :statuses
  resources :book_users
  resources :categories
  resources :books
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "books#index"
end

app/models/book_user.rb
class BookUser < ApplicationRecord
	belongs_to :user 
	belongs_to :book
	belongs_to :status

	after_save :update_book_availability_count

	validates_presence_of :book_id ,:user_id ,:from, :to,:status_id

	validate :check_date
	validate :multiple_borrows, on: :create

	def multiple_borrows
		status_returned_id = Status.where('name=?',"Returned").first.id
		books_borrowed = BookUser.where('user_id=? and book_id=? and status_id !=?', user_id, book_id,status_returned_id)
		if !books_borrowed.empty?
			errors.add(:book_id,"already borrowed and not returned yet!")
		end	
	end
		
	def check_date
		if self.from > self.to 
			errors.add(:to, "date should be greater than from date")
		end

		if self.to < Date.today
			errors.add(:to , "date should be greater than today")
		end 
	end

	def self.create_book_user(id,current_user,book_user)
		book = Book.where('id=?',id).first
		book.with_lock do
			if book.borrowed_count.to_i < book.availability 
				book_user.book_id = book.id
		    book_user.user_id = current_user.id
		    book_user.from = Date.today
		    book_user.to = Date.today + 15.days
		    book_user.status_id = Status.where('name=?',"Borrowed").first.id
		  end  
		end  
	end

	def self.set_current_user_records(current_user)
		if current_user.role == "admin"
			@book_users = BookUser.all
		else
			@book_users = current_user.book_users
		end	    
	end

	def update_book_availability_count
		book = Book.where('id=?',book_id).first
		if status_id == Status.where('name=?',"Borrowed").first.id
			book.borrowed_count = book.borrowed_count.to_i + 1
		elsif status_id == Status.where('name=?',"Returned").first.id
			book.borrowed_count  = book.borrowed_count.to_i - 1
		end
		book.save
	end	

end

app/controllers/book_users_controller.rb
class BookUsersController < ApplicationController
  before_action :set_book_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  # GET /book_users
  # GET /book_users.json
  def index
    @book_users = BookUser.set_current_user_records(current_user)
  end

  # GET /book_users/1
  # GET /book_users/1.json
  def show
  end

  # GET /book_users/new
  def new
    @book_user = BookUser.new
  end

  # GET /book_users/1/edit
  def edit
  end

  # POST /book_users
  # POST /book_users.json
  def create

    @book_user = BookUser.new
    BookUser.create_book_user(params[:id],current_user,@book_user)   
  
    respond_to do |format|
      if @book_user.save
        # format.html { redirect_to @book_user, notice: 'Book user was successfully created.' }
        # format.json { render :show, status: :created, location: @book_user }
        format.js{}
      else
        # format.html { render :new }
        # format.json { render json: @book_user.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  # PATCH/PUT /book_users/1
  # PATCH/PUT /book_users/1.json
  def update
    respond_to do |format|
      if @book_user.update(book_user_params)
        format.html { redirect_to @book_user, notice: 'Book user was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_user }
      else
        format.html { render :edit }
        format.json { render json: @book_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_users/1
  # DELETE /book_users/1.json
  def destroy
    @book_user.destroy
    respond_to do |format|
      format.html { redirect_to book_users_url, notice: 'Book user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_user
      @book_user = BookUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_user_params
      params.require(:book_user).permit(:book_id, :user_id, :from, :to, :status_id)
    end
end

app/helpers/book_users_helper.rb
module BookUsersHelper
	def status_updatable
		status_automated = Status.where(name: ["Borrowed", "Overdue"]).pluck(:id)
		status_allowed = Status.where.not(id: status_automated)
		return status_allowed
	end
end

app/views/book_users/_form.html.erb
<% if current_user.role == "admin" %> 
<%= form_for(book_user) do |f| %>
  <% if book_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_user.errors.count, "error") %> prohibited this book_user from being saved:</h2>

      <ul>
      <% book_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class ="row">
  <div class="col-md-6">

  <div class="field">
    <%= f.label :book_id %>
    <%=  f.collection_select :book_id, Book.all , :id, :name, {prompt:"select book" } , 
    class: "form-control" , required: true , disabled: true %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all , :id, :email, {prompt:"select user" } , 
    class: "form-control" , required: true ,disabled: true %>
  </div>

  <div class="field">
    <%= f.label :from %>
    <%= f.date_select :from , disabled: true%>
  </div>

  <div class="field">
    <%= f.label :to %>
    <%= f.date_select :to %>
  </div>

  <div class="field">
    <%= f.label :status_id %>
    <%= f.collection_select :status_id, status_updatable , :id, :name, {prompt:"select status", include_blank: true } , 
    class: "form-control" , required: true %>
  </div>

  <div class="row">
    <div class="col-md-9">
      <div class="actions">
        <%= f.submit :class => "btn btn-success" %>
      </div>
    </div>
    <div class ="col-md-3">
      <%= link_to 'Cancel', book_users_path ,:class => "btn btn-danger" %>
    </div>
  </div>
  </div>
  </div>
<% end %>
<% end %>

app/views/book_users/create.js.erb
$("#book_index").empty();
$("#book_index").html("<%= escape_javascript(render '/books/tables') %>");

app/views/book_users/edit.html.erb
<h1>Editing Book User</h1>

<%= render 'form', book_user: @book_user %>

<%= link_to 'Show', @book_user %> |
<%= link_to 'Back', book_users_path %>

app/views/book_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>My Books</h1>

<table class="table myTable">
  <thead>
    <tr>
      <th>Book</th>
      <th>User</th>
      <th>From</th>
      <th>To</th>
      <th>Status</th>
      <% if current_user.role == "admin" %>
      <th>Actions</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @book_users.each do |book_user| %>
      <tr>
        <td><%= book_user.book.name%></td>
        <td><%= book_user.user.email %></td>
        <td><%= book_user.from %></td>
        <td><%= book_user.to %></td>
        <td>
        <%= book_user.status.name%>
        <% if book_user.to < Date.today && book_user.status.name != "Returned" %> 
           <p class="red"> Overdue! </p>
        <% end %>
        </td>
        <% if current_user.role == "admin" %>
        <td>
        <%= link_to 'Show', book_user %>|
        <% if book_user.status.name != "Returned" %>
          <%= link_to 'Edit', edit_book_user_path(book_user) %>|
        <% end %>  
        <%#= link_to 'Destroy', book_user, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Book User', new_book_user_path %>

app/views/book_users/new.html.erb
<% if current_user.role == "admin" %> 
<h1>New Book User</h1>

<%= render 'form', book_user: @book_user %>

<%= link_to 'Back', book_users_path %>
<% else %>
You dont have access to  this content!
<% end %>

app/views/book_users/show.html.erb
<% if current_user.role == "admin"%>
<p id="notice"><%= notice %></p>

<p>
  <strong>Book:</strong>
  <%= @book_user.book.name %>
  <%#= @book_user.book_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @book_user.user.email%>
  <%#= @book_user.user_id%>
</p>

<p>
  <strong>From:</strong>
  <%= @book_user.from %>
</p>

<p>
  <strong>To:</strong>
  <%= @book_user.to %>
</p>

<p>
  <strong>Status:</strong>
  <%= @book_user.status.name %>
  <%#= @book_user.status_id %>
</p>

<%= link_to 'Back', book_users_path %>

<% if current_user.role == "admin" && @book_user.status.name != "Returned" %>
  <%= link_to 'Edit', edit_book_user_path(@book_user) %> |
<% end %>  

<% else %>
You dont have access to this content!
<% end %>